version: "2" # required to adjust maintainability checks
plugins:
  sonar-java:
    enabled: true
    config:
      # minimum_severity: info
      sonar.java.source: "8"
      tests_patterns:
        - code/server/src/test/**
