import { AbstractSpecificHero } from './abstract-specific-hero';

/**
 * Hero class
 */
export class Hero {
    // PROPERTIES

    /**
     * Id (primary key in JPA database)
     */
    id: number;

    /**
     * Unique id generated by the server
     */
    uniqueId: string;

    /**
     * Hero name
     */
    name: string;

    /**
     * Hero (ex: Paladin, Warrior, Mage)
     */
    type: string;

    /**
     * Skill type (ex: self, target)
     */
    skillType: string;

    /**
     * Lifepoints (maximum 30)
     */
    lifepoints: number;

    /**
     * Defense (when attacked, defense points will be deducted before lifepoints)
     */
    defense: number;

    /**
     * Hero description
     */
    description: string;

    /**
     * Specific hero implementation
     */
    specificHero: AbstractSpecificHero;

    /**
     * Boolean indicating ability to use special skill
     */
    canUseSpecialSkill: boolean;
}
