var searchData=
[
  ['basiccard',['BasicCard',['../classminihearthstone_1_1entities_1_1cards_1_1_basic_card.html',1,'minihearthstone.entities.cards.BasicCard'],['../classminihearthstone_1_1entities_1_1cards_1_1_basic_card.html#a069aefa0d8309a42ed752d40236732cb',1,'minihearthstone.entities.cards.BasicCard.BasicCard()'],['../classminihearthstone_1_1entities_1_1cards_1_1_basic_card.html#aeb315e1f50ee6975e04c451d5a55d87c',1,'minihearthstone.entities.cards.BasicCard.BasicCard(String uniqueId, String name, int manacost, int damage, int lifepoints, boolean canAttack, int defense, String type, String nature, AbstractEffect effect, AbstractSpecificCard specificCard)'],['../classminihearthstone_1_1entities_1_1cards_1_1_basic_card.html#acfd3910f1c53d648608d0c1d3f199519',1,'minihearthstone.entities.cards.BasicCard.BasicCard(String name, int manacost, int damage, int lifepoints, String type, String nature, AbstractEffect effect, AbstractSpecificCard specificCard)'],['../classminihearthstone_1_1entities_1_1cards_1_1_basic_card.html#a365d290d18fdfb164ce0882958785120',1,'minihearthstone.entities.cards.BasicCard.BasicCard(Long id, String uniqueId, String name, int manacost, int damage, int lifepoints, String type, String nature, String description, Deck deck, GameBoard gbP1HandOfCardsMapping, GameBoard gbP2HandOfCardsMapping, GameBoard gbP1CardsOnGroundMapping, GameBoard gbP2CardsOnGroundMapping, AbstractEffect effect, AbstractSpecificCard specificCard)']]],
  ['basiccard_2ejava',['BasicCard.java',['../_basic_card_8java.html',1,'']]],
  ['basiceffect',['BasicEffect',['../classminihearthstone_1_1entities_1_1cards_1_1effects_1_1_basic_effect.html',1,'minihearthstone.entities.cards.effects.BasicEffect'],['../classminihearthstone_1_1entities_1_1cards_1_1effects_1_1_basic_effect.html#a0ab9991743e8b674156851bce574826e',1,'minihearthstone.entities.cards.effects.BasicEffect.BasicEffect()']]],
  ['basiceffect_2ejava',['BasicEffect.java',['../_basic_effect_8java.html',1,'']]],
  ['basichero',['BasicHero',['../classminihearthstone_1_1entities_1_1heroes_1_1_basic_hero.html',1,'minihearthstone.entities.heroes.BasicHero'],['../classminihearthstone_1_1entities_1_1heroes_1_1_basic_hero.html#a0b4d01d0f8cde379455f1202df1eab14',1,'minihearthstone.entities.heroes.BasicHero.BasicHero()'],['../classminihearthstone_1_1entities_1_1heroes_1_1_basic_hero.html#aa9df77befb383d5f31c07ddc72b10cdb',1,'minihearthstone.entities.heroes.BasicHero.BasicHero(String name, String type, String skillType, AbstractSpecificHero specificHero, String description)']]],
  ['basichero_2ejava',['BasicHero.java',['../_basic_hero_8java.html',1,'']]],
  ['benedictiondepuissance',['BenedictionDePuissance',['../classminihearthstone_1_1entities_1_1cards_1_1_benediction_de_puissance.html',1,'minihearthstone.entities.cards.BenedictionDePuissance'],['../classminihearthstone_1_1entities_1_1cards_1_1_benediction_de_puissance.html#a42f95646116feab7e370e21408c96f9c',1,'minihearthstone.entities.cards.BenedictionDePuissance.BenedictionDePuissance()']]],
  ['benedictiondepuissance_2ejava',['BenedictionDePuissance.java',['../_benediction_de_puissance_8java.html',1,'']]]
];
